version: "3.8"
services:
  frontend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.frontend
    container_name: my-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

  backend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.backend
    container_name: my-backend
    ports:
      - "8080:8080"

  db:
    image: postgres:15
    container_name: my-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - ./database/docker-init-scripts:/docker-entrypoint-initdb.d
