name: CI

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Use Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install frontend deps
        run: |
          cd frontend
          npm install
          npm run lint
          npm run build
          npm run test # si configuras tests

      - name: Install backend deps
        run: |
          cd backend
          npm install
          npm run lint  # si configuras lint
          npm run build
          npm run test  # si configuras tests
